=== iimanol7/web-reto3/xml/clasificacion.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="clasificacion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="posicion" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="temp" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="posicion">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="equipo"/>
        <xs:element name="puntos" type="xs:integer"/>
        <xs:element name="jugados" type="xs:integer"/>
        <xs:element name="ganados" type="xs:integer"/>
        <xs:element name="empatados" type="xs:integer"/>
        <xs:element name="perdidos" type="xs:integer"/>
        <xs:element name="goles-favor" type="xs:integer"/>
        <xs:element name="goles-contra" type="xs:integer"/>
      </xs:sequence>
      <xs:attribute name="num" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="equipo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="escudo" type="xs:string"/>
        <xs:element name="nombre" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== iimanol7/web-reto3/xml/clasificacion_Temporada 2.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="clasificacion.xsl"?>
<clasificacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="clasificacion.xsd" temp="Temporada 2">
 <posicion num="1">
 	<equipo>
			<escudo>Base Sevilla.png</escudo>
			<nombre>Base Sevilla</nombre>
 	</equipo>
 	<puntos>15</puntos>
		<jugados>10</jugados>
  	<ganados>3</ganados>
 	 <empatados>6</empatados>
 	<perdidos>1</perdidos>
  	<goles-favor>44</goles-favor>
     <goles-contra>48</goles-contra>
 </posicion>
 <posicion num="2">
 	<equipo>
			<escudo>Real Zaragoza.png</escudo>
			<nombre>Real Zaragoza</nombre>
 	</equipo>
 	<puntos>14</puntos>
		<jugados>10</jugados>
  	<ganados>3</ganados>
 	 <empatados>5</empatados>
 	<perdidos>2</perdidos>
  	<goles-favor>19</goles-favor>
     <goles-contra>17</goles-contra>
 </posicion>
 <posicion num="3">
 	<equipo>
			<escudo>Athletic.png</escudo>
			<nombre>Athletic</nombre>
 	</equipo>
 	<puntos>14</puntos>
		<jugados>10</jugados>
  	<ganados>2</ganados>
 	 <empatados>8</empatados>
 	<perdidos>0</perdidos>
  	<goles-favor>54</goles-favor>
     <goles-contra>22</goles-contra>
 </posicion>
 <posicion num="4">
 	<equipo>
			<escudo>Real Madrid.png</escudo>
			<nombre>Real Madrid</nombre>
 	</equipo>
 	<puntos>11</puntos>
		<jugados>10</jugados>
  	<ganados>2</ganados>
 	 <empatados>5</empatados>
 	<perdidos>3</perdidos>
  	<goles-favor>49</goles-favor>
     <goles-contra>52</goles-contra>
 </posicion>
 <posicion num="5">
 	<equipo>
			<escudo>FCBarcelona.png</escudo>
			<nombre>FCBarcelona</nombre>
 	</equipo>
 	<puntos>9</puntos>
		<jugados>10</jugados>
  	<ganados>1</ganados>
 	 <empatados>6</empatados>
 	<perdidos>3</perdidos>
  	<goles-favor>18</goles-favor>
     <goles-contra>42</goles-contra>
 </posicion>
 <posicion num="6">
 	<equipo>
			<escudo>Ciudad de Salamanca.png</escudo>
			<nombre>Ciudad de Salamanca</nombre>
 	</equipo>
 	<puntos>9</puntos>
		<jugados>10</jugados>
  	<ganados>1</ganados>
 	 <empatados>6</empatados>
 	<perdidos>3</perdidos>
  	<goles-favor>18</goles-favor>
     <goles-contra>21</goles-contra>
 </posicion>
</clasificacion>

=== iimanol7/web-reto3/ELIMINADOS/clasificacionn.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="clasificacion.xsl"?>
<clasificacion xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml/clasificacion.xsd" temp="temporada 1">
    
    <posicion num="1">
        <equipo>
            <escudo>bilbao.png</escudo>
            <nombre>Bilbao</nombre>
        </equipo>
        <puntos>3</puntos>
        <jugados>1</jugados>
        <ganados>1</ganados>
        <empatados>0</empatados>
        <perdidos>0</perdidos>
        <goles-favor>4</goles-favor>
        <goles-contra>2</goles-contra>
    </posicion>
    <posicion num="2">
        <equipo>
            <escudo>Barcelona.png</escudo>
            <nombre>Barcelona</nombre>
        </equipo>
        <puntos>0</puntos>
        <jugados>1</jugados>
        <ganados>0</ganados>
        <empatados>0</empatados>
        <perdidos>1</perdidos>
        <goles-favor>2</goles-favor>
        <goles-contra>4</goles-contra>
    </posicion>
    <posicion num="3">
        <equipo>
            <escudo>madrid.png</escudo>
            <nombre>Madrid</nombre>
        </equipo>
        <puntos>0</puntos>
        <jugados>0</jugados>
        <ganados>0</ganados>
        <empatados>0</empatados>
        <perdidos>0</perdidos>
        <goles-favor>0</goles-favor>
        <goles-contra>0</goles-contra>
    </posicion>
    <posicion num="4">
        <equipo>
            <escudo>zaragoza.png</escudo>
            <nombre>Zaragoza</nombre>
        </equipo>
        <puntos>0</puntos>
        <jugados>0</jugados>
        <ganados>0</ganados>
        <empatados>0</empatados>
        <perdidos>0</perdidos>
        <goles-favor>0</goles-favor>
        <goles-contra>0</goles-contra>
    </posicion>
    <posicion num="5">
        <equipo>
            <escudo>salamanca.png</escudo>
            <nombre>Salamanca</nombre>
        </equipo>
        <puntos>0</puntos>
        <jugados>0</jugados>
        <ganados>0</ganados>
        <empatados>0</empatados>
        <perdidos>0</perdidos>
        <goles-favor>0</goles-favor>
        <goles-contra>0</goles-contra>
    </posicion>
    <posicion num="6">
        <equipo>
            <escudo>sevilla.png</escudo>
            <nombre>Sevilla</nombre>
        </equipo>
        <puntos>0</puntos>
        <jugados>0</jugados>
        <ganados>0</ganados>
        <empatados>0</empatados>
        <perdidos>0</perdidos>
        <goles-favor>0</goles-favor>
        <goles-contra>0</goles-contra>
    </posicion>
</clasificacion>
