=== iimanol7/web-reto3/xml/equipos.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="equipos">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="equipo" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="temp" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="equipo">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="escudo" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== iimanol7/web-reto3/xml/equipos_Temporada 3.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="equipos.xsl"?>
<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="equipos.xsd" temp="Temporada 3">
  <equipo id="equipo1">
  	<nombre>Athletic</nombre>
  	<escudo>Athletic.png</escudo>
	</equipo>
  <equipo id="equipo2">
  	<nombre>FCBarcelona</nombre>
  	<escudo>FCBarcelona.png</escudo>
	</equipo>
  <equipo id="equipo3">
  	<nombre>Real Madrid</nombre>
  	<escudo>Real Madrid.png</escudo>
	</equipo>
  <equipo id="equipo4">
  	<nombre>Real Zaragoza</nombre>
  	<escudo>Real Zaragoza.png</escudo>
	</equipo>
  <equipo id="equipo5">
  	<nombre>Ciudad de Salamanca</nombre>
  	<escudo>Ciudad de Salamanca.png</escudo>
	</equipo>
  <equipo id="equipo6">
  	<nombre>Base Sevilla</nombre>
  	<escudo>Base Sevilla.png</escudo>
	</equipo>
</equipos>

=== iimanol7/web-reto3/ELIMINADOS/equipos.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="equipos.xsl"?>
<!--  -->
<!-- <?xml-model href="xml/equipos.xsd"?> -->
<!--  -->
<equipos xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../xml/equipos.xsd" temp="1">

    <equipo id="equipo1" ruta="bilbao.xml">
        <nombre>Bilbao</nombre>
        <escudo>bilbao.png</escudo>
    </equipo>
    <equipo id="equipo2" ruta="barcelona.xml">
        <nombre>Barcelona</nombre>
        <escudo>barcelona.png</escudo>
    </equipo>
    <equipo id="equipo3" ruta="madrid.xml">
        <nombre>Madrid</nombre>
        <escudo>madrid.png</escudo>
    </equipo>
    <equipo id="equipo4" ruta="zaragoza.xml">
        <nombre>Zaragoza</nombre>
        <escudo>zaragoza.png</escudo>
    </equipo>
    <equipo id="equipo5" ruta="salamanca.xml">
        <nombre>Salamanca</nombre>
        <escudo>salamanca.png</escudo>
    </equipo>
    <equipo id="equipo6" ruta="sevilla.xml">
        <nombre>Sevilla</nombre>
        <escudo>sevilla.png</escudo>
    </equipo>

</equipos>
