=== iimanol7/web-reto3/xml/validacion-equipo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="equipo">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="componente" maxOccurs="unbounded"/>
      </xs:sequence>
      <xs:attribute name="escudo" type="xs:string" use="required"/>
      <xs:attribute name="nombre" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="componente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="imagen" type="xs:string"/>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="apellidos" type="xs:string"/>
        <xs:element name="posicion" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="tipo" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== iimanol7/web-reto3/xml/Athletic.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo-equipo.xsl"?>
<equipo nombre="ATHLETIC" escudo="../img/Athletic.png" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validacion-equipo.xsd">

    <componente tipo="entrenador">
        <imagen>e1.png</imagen>
        <nombre>Garazi</nombre>
        <apellidos>Arrumbarrena</apellidos>
        <posicion>null</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j1.png</imagen>
        <nombre>Carmen</nombre>
        <apellidos>Campos</apellidos>
        <posicion>Portera</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j2.png</imagen>
        <nombre>Ángelica</nombre>
        <apellidos>Buenache</apellidos>
        <posicion>Lateral Izquierdo</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j3.png</imagen>
        <nombre>Laura</nombre>
        <apellidos>Gil</apellidos>
        <posicion>Lateral Derecho</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j4.png</imagen>
        <nombre>Sara</nombre>
        <apellidos>Higuero</apellidos>
        <posicion>Extremo Izquierda</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j5.png</imagen>
        <nombre>Ángela</nombre>
        <apellidos>Montejo</apellidos>
        <posicion>Extremo Derecha</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j6.png</imagen>
        <nombre>Celia</nombre>
        <apellidos>Acuña</apellidos>
        <posicion>Pivote</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j7.png</imagen>
        <nombre>Nerea</nombre>
        <apellidos>Pozo</apellidos>
        <posicion>Central</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j8.png</imagen>
        <nombre>Adriana </nombre>
        <apellidos>Flores</apellidos>
        <posicion>Extremo derecha</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j9.png</imagen>
        <nombre>Isabel </nombre>
        <apellidos>Vargas</apellidos>
        <posicion>Lateral izquierdo</posicion>
    </componente>
    
</equipo>

=== iimanol7/web-reto3/xml/FCBarcelona.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo-equipo.xsl"?>
<equipo nombre="FCBARCELONA" escudo="../img/FCBarcelona.png" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validacion-equipo.xsd">

    <componente tipo="entrenador">
        <imagen>e2.png</imagen>
        <nombre>Alicia </nombre>
        <apellidos>Montjuic</apellidos>
        <posicion>null</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j10.png</imagen>
        <nombre>Merche </nombre>
        <apellidos>Castellano</apellidos>
        <posicion>Portera</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j11.png</imagen>
        <nombre>Sandra</nombre>
        <apellidos>Paños</apellidos>
        <posicion>Lateral Izquierdo</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j12.png</imagen>
        <nombre>Lucy </nombre>
        <apellidos>Bronze</apellidos>
        <posicion>Lateral Derecho</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j13.png</imagen>
        <nombre>Marta </nombre>
        <apellidos>Torrejón</apellidos>
        <posicion>Extremo Izquierda</posicion>

    </componente>

    <componente tipo="jugador">
        <imagen>j14.png</imagen>
        <nombre>Olga </nombre>
        <apellidos>García</apellidos>
        <posicion>Extremo Derecha</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j15.png</imagen>
        <nombre>Mapi</nombre>
        <apellidos>León </apellidos>
        <posicion>Pivote</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j16.png</imagen>
        <nombre>Alexia </nombre>
        <apellidos>Putellas </apellidos>
        <posicion>Central</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j17.png</imagen>
        <nombre>María  </nombre>
        <apellidos>García </apellidos>
        <posicion>Central</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j18.png</imagen>
        <nombre>Laura </nombre>
        <apellidos>Rodríguez </apellidos>
        <posicion>Extremo derecha</posicion>
    </componente>
    
</equipo>

=== iimanol7/web-reto3/xml/Real Madrid.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo-equipo.xsl"?>
<equipo nombre="REAL MADRID" escudo="../img/Real Madrid.png" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validacion-equipo.xsd">

    <componente tipo="entrenador">
        <imagen>e3.png</imagen>
        <nombre>Beñat </nombre>
        <apellidos>Arnaiz </apellidos>
        <posicion>null</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j19.png</imagen>
        <nombre>Alba </nombre>
        <apellidos>Sánchez </apellidos>
        <posicion>Portera</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j20.png</imagen>
        <nombre>Ane </nombre>
        <apellidos>Encina</apellidos>
        <posicion>Lateral Izquierdo</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j21.png</imagen>
        <nombre>Estitxu </nombre>
        <apellidos>Berasategi</apellidos>
        <posicion>Lateral Derecho</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j22.png</imagen>
        <nombre>Paula </nombre>
        <apellidos>García </apellidos>
        <posicion>Extremo Izquierda</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j23.png</imagen>
        <nombre>Ana </nombre>
        <apellidos>Arozamena </apellidos>
        <posicion>Extremo Derecha</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j24.png</imagen>
        <nombre>Maddi </nombre>
        <apellidos>Bengoetxea </apellidos>
        <posicion>Pivote</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j25.png</imagen>
        <nombre>Silvia </nombre>
        <apellidos>Arderíus </apellidos>
        <posicion>Central</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j26.png</imagen>
        <nombre>Beatriz  </nombre>
        <apellidos>Jiménez </apellidos>
        <posicion>Portera</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j27.png</imagen>
        <nombre>Vanessa  </nombre>
        <apellidos>Torres </apellidos>
        <posicion>Lateral derecho</posicion>
    </componente>
    
</equipo>

=== iimanol7/web-reto3/xml/Ciudad de Salamanca.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo-equipo.xsl"?>
<equipo nombre="SALAMANCA" escudo="../img/Ciudad de Salamanca.png" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validacion-equipo.xsd">

    <componente tipo="entrenador">
        <imagen>e5.png</imagen>
        <nombre>Enara </nombre>
        <apellidos>Robles </apellidos>
        <posicion>null</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j28.png</imagen>
        <nombre>Amaya </nombre>
        <apellidos>Valdemoro </apellidos>
        <posicion>Portera</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j29.png</imagen>
        <nombre>Shay </nombre>
        <apellidos>Murphy </apellidos>
        <posicion>Lateral Izquierdo</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j30.png</imagen>
        <nombre>Roneeka </nombre>
        <apellidos>Hodges</apellidos>
        <posicion>Lateral Derecho</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j31.png</imagen>
        <nombre>Erika </nombre>
        <apellidos>da Souza</apellidos>
        <posicion>Extremo Izquierda</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j32.png</imagen>
        <nombre>Anna </nombre>
        <apellidos>Montañana</apellidos>
        <posicion>Extremo Derecha</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j6.png</imagen>
        <nombre>Ester </nombre>
        <apellidos>Somaza</apellidos>
        <posicion>Pivote</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j33.png</imagen>
        <nombre>Nuria </nombre>
        <apellidos>Martínez </apellidos>
        <posicion>Central</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j34.png</imagen>
        <nombre>Claudia  </nombre>
        <apellidos>Ramírez </apellidos>
        <posicion>Central</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j36.png</imagen>
        <nombre>Carolina  </nombre>
        <apellidos>Sánchez </apellidos>
        <posicion>Portera</posicion>
    </componente>
    
</equipo>

=== iimanol7/web-reto3/xml/Real Zaragoza.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo-equipo.xsl"?>
<equipo nombre="ZARAGOZA" escudo="../img/Real Zaragoza.png" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validacion-equipo.xsd">

    <componente tipo="entrenador">
        <imagen>e4.png</imagen>
        <nombre>Claudio </nombre>
        <apellidos>Ramos </apellidos>
        <posicion>null</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j46.png</imagen>
        <nombre>Raquel </nombre>
        <apellidos>Caño </apellidos>
        <posicion>Portera</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j47.png</imagen>
        <nombre>Mireya  </nombre>
        <apellidos>Gónzalez </apellidos>
        <posicion>Lateral Izquierdo</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j48.png</imagen>
        <nombre>Deonise  </nombre>
        <apellidos>Fachinello   </apellidos>
        <posicion>Lateral Derecho</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j49.png</imagen>
        <nombre>Soraya  </nombre>
        <apellidos>García  </apellidos>
        <posicion>Extremo Izquierda</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j50.png</imagen>
        <nombre>Anna </nombre>
        <apellidos>Gonzales</apellidos>
        <posicion>Extremo Derecha</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j51.png</imagen>
        <nombre>Ona  </nombre>
        <apellidos>Vegue  </apellidos>
        <posicion>Pivote</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j52.png</imagen>
        <nombre>María  </nombre>
        <apellidos>Prieto  </apellidos>
        <posicion>Central</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j53.png</imagen>
        <nombre>Ana   </nombre>
        <apellidos>López  </apellidos>
        <posicion>Portera</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j54.png</imagen>
        <nombre>Patricia   </nombre>
        <apellidos>Martínez  </apellidos>
        <posicion>Lateral izquierdo</posicion>
    </componente>
    
</equipo>

=== iimanol7/web-reto3/xml/Base Sevilla.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="estilo-equipo.xsl"?>
<equipo nombre="SEVILLA" escudo="../img/Base Sevilla.png" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="validacion-equipo.xsd">

    <componente tipo="entrenador">
        <imagen>e6.png</imagen>
        <nombre>Mariano </nombre>
        <apellidos>Sanchez</apellidos>
        <posicion>null</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j37.png</imagen>
        <nombre>Lara </nombre>
        <apellidos>González </apellidos>
        <posicion>Portera</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j38.png</imagen>
        <nombre>Maitane </nombre>
        <apellidos>Etxeberria </apellidos>
        <posicion>Lateral Izquierdo</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j39.png</imagen>
        <nombre>Amaia </nombre>
        <apellidos>González </apellidos>
        <posicion>Lateral Derecho</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j40.png</imagen>
        <nombre>Jennifer </nombre>
        <apellidos>Gutiérrez</apellidos>
        <posicion>Extremo Izquierda</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j41.png</imagen>
        <nombre>Anna </nombre>
        <apellidos>Montañana </apellidos>
        <posicion>Extremo Derecha</posicion>
    </componente>

    <componente tipo="jugador">
        <imagen>j42.png</imagen>
        <nombre>Mireya </nombre>
        <apellidos>González </apellidos>
        <posicion>Pivote</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j43.png</imagen>
        <nombre>Ester </nombre>
        <apellidos>Somaza </apellidos>
        <posicion>Central</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j44.png</imagen>
        <nombre>Sandra  </nombre>
        <apellidos>González </apellidos>
        <posicion>Portera</posicion>
    </componente>
    <componente tipo="jugador">
        <imagen>j45.png</imagen>
        <nombre>Gabriela  </nombre>
        <apellidos>Pérez </apellidos>
        <posicion>Pivote</posicion>
    </componente>
    
</equipo>
